baseURL = "https://blog.marcocadete.com/"
languageCode = "en-us"
title = "Marco Cadete"
copyright= "Marco Cadete and blog.marcocadete.com, 2021. Unauthorized use and/or duplication of this material without express and written permission from this site’s author and/or owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to Marco Cadete and blog.marcocadete.com with appropriate and specific direction to the original content."

disableKinds = ["taxonomyTerm"]

[taxonomies]
    category = "categories"

[outputs]
    home = ["JSON", "HTML", "RSS"]
