baseURL = "https://blog.marcocadete.com/"
languageCode = "en-us"
title = "Marco Cadete"

disableKinds = ["taxonomyTerm"]

[taxonomies]
    category = "categories"

[outputs]
    home = ["JSON", "HTML", "RSS"]
